version: '3'
services:
  postgresql:
    container_name: postgresql_db
    image: postgres:15
    environment:
      - POSTGRES_HOST_AUTH_METHOD="trust"
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - POSTGRES_PASSWORD="postgres"
    ports:
      - "5432:5432"
